import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ms' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  ms: {
    // Nav
    'Home': 'Utama',
    'About Us': 'Tentang Kami',
    'Products': 'Produk',
    'Services': 'Perkhidmatan',
    'Gallery': 'Galeri',
    'Sustainability': 'Kelestarian',
    'News': 'Berita',
    'Careers': 'Kerjaya',
    'FAQ': 'Soalan Lazim',
    'Contact': 'Hubungi',
    // Layout
    'Follow us:': 'Ikuti kami:',
    'Quick Links': 'Pautan Pantas',
    'Contact Info': 'Maklumat Hubungan',
    'Newsletter': 'Surat Berita',
    'Subscribe for seasonal updates and farm news.': 'Langgan untuk kemas kini bermusim dan berita ladang.',
    'Your email address': 'Alamat e-mel anda',
    'Subscribe': 'Langgan',
    'Privacy Policy': 'Dasar Privasi',
    'Terms of Service': 'Terma Perkhidmatan',
    // Home
    'Cultivating Excellence,<br />Nurturing Nature.': 'Memupuk Kecemerlangan,<br />Menyuburkan Alam Sekitar.',
    'Welcome to Usin Farm Enterprise. Premium agriculture, sustainable practices, and fresh produce straight from our fields to your table.': 'Selamat datang ke Usin Farm Enterprise. Pertanian premium, amalan lestari, dan hasil segar terus dari ladang kami ke meja anda.',
    'Explore Our Produce': 'Terokai Hasil Kami',
    'Discover Our Story': 'Ketahui Kisah Kami',
    'Why Choose Usin Farm?': 'Mengapa Memilih Usin Farm?',
    '100% Organic': '100% Organik',
    'Our crops are grown without synthetic pesticides or fertilizers, ensuring pure, natural goodness.': 'Tanaman kami ditanam tanpa racun perosak atau baja sintetik, menjamin kebaikan semula jadi yang tulen.',
    'Sustainable Methods': 'Kaedah Lestari',
    'We employ eco-friendly farming techniques that enrich the soil and protect local biodiversity.': 'Kami menggunakan teknik pertanian mesra alam yang menyuburkan tanah dan melindungi biodiversiti tempatan.',
    'Fresh Daily': 'Segar Setiap Hari',
    'Harvested at the peak of ripeness and delivered fresh, guaranteeing maximum nutrition and flavor.': 'Dituai pada tahap kematangan optimum dan dihantar segar, menjamin nutrisi dan rasa yang maksimum.',
    'A Legacy of Quality Farming': 'Legasi Pertanian Berkualiti',
    'At Usin Farm Enterprise, agriculture isn\'t just an industry—it\'s our heritage. Spanning acres of fertile land, our farm combines traditional wisdom with modern innovation to cultivate crops and raise livestock of unparalleled quality.': 'Di Usin Farm Enterprise, pertanian bukan sekadar industri—ia adalah warisan kami. Meliputi ekar tanah yang subur, ladang kami menggabungkan kebijaksanaan tradisional dengan inovasi moden untuk mengusahakan tanaman dan menternak haiwan berkualiti tinggi.',
    'Premium Livestock Breeding': 'Pembiakan Ternakan Premium',
    'Seasonal Organic Vegetables': 'Sayuran Organik Bermusim',
    'Advanced Irrigation Systems': 'Sistem Pengairan Termaju',
    'Community-Supported Agriculture': 'Pertanian Sokongan Komuniti',
    'Learn More About Us': 'Ketahui Lebih Lanjut Tentang Kami',
    'Years of<br/>Excellence': 'Tahun<br/>Kecemerlangan',
    // About
    'About Usin Farm': 'Mengenai Usin Farm',
    'Rooted in tradition, growing towards the future.': 'Berakar umbi pada tradisi, berkembang ke arah masa depan.',
    'Our History': 'Sejarah Kami',
    'Founded on a deep respect for the land, Usin Farm Enterprise began as a humble family endeavor. Over the years, we have expanded our acreage and our expertise, transforming into a premier agricultural supplier.': 'Diasaskan dengan rasa hormat yang mendalam terhadap tanah, Usin Farm Enterprise bermula sebagai usaha keluarga yang sederhana. Selama bertahun-tahun, kami telah meluaskan keluasan dan kepakaran kami, berubah menjadi pembekal pertanian terkemuka.',
    'Despite our growth, our core philosophy remains unchanged: to work in harmony with nature to produce food that is healthy for both our community and our planet.': 'Walaupun berkembang, falsafah teras kami kekal tidak berubah: untuk bekerja secara harmoni dengan alam semula jadi bagi menghasilkan makanan yang sihat untuk kedua-dua komuniti dan planet kita.',
    'Acres of Land': 'Ekar Tanah',
    'Happy Customers': 'Pelanggan Gembira',
    'Our Mission': 'Misi Kami',
    'To cultivate premium quality agricultural products through sustainable and innovative farming practices, ensuring food security and nutrition for our community.': 'Untuk memupuk produk pertanian berkualiti premium melalui amalan pertanian yang mampan dan inovatif, memastikan keselamatan makanan dan nutrisi untuk komuniti kami.',
    'Our Vision': 'Visi Kami',
    'To be the leading recognized model of sustainable and regenerative agriculture in the region, inspiring a greener, healthier world.': 'Untuk menjadi model yang diiktiraf terkemuka dalam pertanian mampan dan regeneratif di rantau ini, memberi inspirasi kepada dunia yang lebih hijau dan sihat.',
    'Core Values': 'Nilai Teras',
    'Integrity in our methods, transparency with our consumers, and an unwavering commitment to environmental stewardship.': 'Integriti dalam kaedah kami, ketelusan dengan pengguna kami, dan komitmen yang tidak berbelah bahagi kepada pengawasan alam sekitar.',
    'Community First': 'Utamakan Komuniti',
    'We believe a farm is the heart of a community. We actively support local initiatives and prioritize fair labor practices.': 'Kami percaya ladang adalah nadi sesebuah komuniti. Kami secara aktif menyokong inisiatif tempatan dan mengutamakan amalan buruh yang adil.',
    // Products
    'Our Products & Livestock': 'Produk & Ternakan Kami',
    'From our farm straight to you. Explore the range of fresh, healthy, and high-quality livestock produce from Usin Farm Enterprise.': 'Dari ladang terus kepada anda. Terokai rangkaian hasil ternakan yang segar, sihat dan berkualiti tinggi dari Usin Farm Enterprise.',
    'Cattle Farming': 'Penternakan Lembu',
    'Quality Beef Cattle': 'Lembu Pedaging Berkualiti',
    'Local & Crossbreed Cattle': 'Baka Lembu Tempatan & Kacukan',
    'Healthy & Well-cared': 'Penjagaan Rapi & Sihat',
    'Broiler Chicken': 'Ayam Daging',
    'Fresh Broiler Meat': 'Ayam Daging Segar',
    'High Quality Diet': 'Diet Berkualiti Tinggi',
    'Optimum Growth': 'Tumbesaran Optimum',
    'Free-range Chicken': 'Ayam Kampung',
    'Authentic Free-range Chicken': 'Ayam Kampung Asli',
    'Free-roaming Farm': 'Ternakan Lepas Bebas',
    'Firm & Tasty Meat': 'Isi Pejal & Sedap',
    'Duck Farming': 'Penternakan Itik',
    'Meat Ducks': 'Itik Pedaging',
    'Laying Ducks': 'Itik Penelur',
    'Clean Farming Environment': 'Persekitaran Ternakan Yang Bersih',
    'Fresh Duck Eggs': 'Telur Itik Segar',
    'Grade A Fresh Duck Eggs': 'Telur Itik Segar Gred A',
    'Beautiful & Quality Yolks': 'Kuning Telur Cantik & Berkualiti',
    'Rich in Nutrients': 'Kaya Nutrisi',
    'Salted Eggs': 'Telur Masin',
    'Authentic Salted Eggs': 'Telur Masin Asli',
    'Traditional Processing': 'Pemprosesan Tradisional',
    'Suitable for Various Dishes': 'Sesuai Untuk Pelbagai Hidangan',
    'Contact Us': 'Hubungi Kami',
    // Services
    'Farm Services': 'Perkhidmatan Ladang',
    'Beyond growing premium crops, Usin Farm Enterprise provides essential services to support the broader agricultural ecosystem and community.': 'Selain mengusahakan tanaman premium, Usin Farm Enterprise menyediakan perkhidmatan penting untuk menyokong ekosistem pertanian dan komuniti yang lebih luas.',
    'Wholesale Delivery': 'Penghantaran Borong',
    'Reliable, temperature-controlled delivery of fresh produce and meats directly to restaurants, supermarkets, and local businesses.': 'Penghantaran hasil segar dan daging dengan kawalan suhu yang boleh dipercayai terus ke restoran, pasar raya dan perniagaan tempatan.',
    'Agricultural Consultation': 'Perundingan Pertanian',
    'Expert advice on crop rotation, soil health, and sustainable farming methods for new and transitioning farmers.': 'Nasihat pakar mengenai penggiliran tanaman, kesihatan tanah dan kaedah pertanian mampan untuk petani baru dan yang sedang beralih.',
    'Storage Solutions': 'Penyelesaian Penyimpanan',
    'State-of-the-art cold storage and grain silos available for seasonal rent to help manage harvest overflow.': 'Penyimpanan sejuk dan silo bijirin terkini yang tersedia untuk sewaan bermusim bagi membantu menguruskan lebihan hasil tuaian.',
    'Farm Tours & Education': 'Lawatan Ladang & Pendidikan',
    'Immersive guided tours for schools and families to learn about where their food comes from and how it\'s grown.': 'Lawatan berpandu yang menarik untuk sekolah dan keluarga untuk mengetahui dari mana makanan mereka datang dan bagaimana ia ditanam.',
    'Inquire Now &rarr;': 'Tanya Sekarang &rarr;',
    // Gallery
    'Farm Gallery': 'Galeri Ladang',
    'Take a visual tour through Usin Farm Enterprise. From our golden harvests to our healthy livestock.': 'Lakukan lawatan visual melalui Usin Farm Enterprise. Dari hasil tuaian emas kami hingga ke ternakan yang sihat.',
    'Play Video': 'Mainkan Video',
    'View Image': 'Lihat Gambar',
    // Sustainability
    'Our Commitment to the Earth': 'Komitmen Kami Terhadap Bumi',
    'At Usin Farm, we believe that true agricultural success is measured by the health of the ecosystem. We have implemented comprehensive sustainable practices to ensure our land remains fertile for generations.': 'Di Usin Farm, kami percaya bahawa kejayaan pertanian yang sebenar diukur oleh kesihatan ekosistem. Kami telah melaksanakan amalan mampan yang komprehensif untuk memastikan tanah kami kekal subur untuk generasi akan datang.',
    'Read Our Impact Report': 'Baca Laporan Impak Kami',
    'Key Initiatives': 'Inisiatif Utama',
    'Zero Waste': 'Sifar Sisa',
    'Composting all organic waste to create natural fertilizers.': 'Mengkompos semua sisa organik untuk menghasilkan baja semula jadi.',
    'Water Conservation': 'Pemuliharaan Air',
    'Advanced drip irrigation reducing water usage by 40%.': 'Sistem pengairan titis termaju mengurangkan penggunaan air sebanyak 40%.',
    'Solar Powered': 'Dikuasakan Solar',
    'Our facilities operate on 100% renewable solar energy.': 'Kemudahan kami beroperasi menggunakan 100% tenaga solar yang boleh diperbaharui.',
    'Soil Health': 'Kesihatan Tanah',
    'Practicing crop rotation to maintain rich, nutrient-dense soil.': 'Mengamalkan penggiliran tanaman untuk mengekalkan tanah yang kaya dan padat dengan nutrien.',
    // News
    'Farm News': 'Berita Ladang',
    'Stay updated with the latest happenings, seasonal harvests, and agricultural innovations at Usin Farm.': 'Kekal mengetahui dengan perkembangan terkini, hasil tuaian bermusim dan inovasi pertanian di Usin Farm.',
    'Spring Harvest Festival Announced': 'Pesta Menuai Musim Bunga Diumumkan',
    'May 15, 2025': '15 Mei 2025',
    'Join us for our annual harvest festival featuring farm tours, local artisan markets, and live music.': 'Sertai kami untuk pesta menuai tahunan yang menampilkan lawatan ladang, pasar kraf tempatan dan muzik secara langsung.',
    'New Sustainable Irrigation System Installed': 'Sistem Pengairan Mampan Baru Dipasang',
    'April 22, 2025': '22 April 2025',
    'We\'re excited to announce the completion of our new smart irrigation project, reducing water waste by 40%.': 'Kami gembira mengumumkan penyelesaian projek pengairan pintar baru kami, yang mengurangkan pembaziran air sebanyak 40%.',
    'Usin Farm Awarded Organic Certification': 'Usin Farm Dianugerahkan Pensijilan Organik',
    'March 10, 2025': '10 Mac 2025',
    'After years of dedication, we have officially received our regional Organic Farm certification.': 'Selepas bertahun-tahun berdedikasi, kami secara rasminya telah menerima pensijilan Ladang Organik serantau.',
    'Read More &rarr;': 'Baca Lanjut &rarr;',
    // Careers
    'Join Our Team': 'Sertai Pasukan Kami',
    'Grow your career with us. We\'re always looking for passionate individuals who care about sustainable agriculture.': 'Kembangkan kerjaya anda bersama kami. Kami sentiasa mencari individu yang bersemangat dan mengambil berat tentang pertanian mampan.',
    'Open Positions': 'Jawatan Kosong',
    'Senior Agronomist': 'Ahli Agronomi Kanan',
    'Full-Time': 'Sepenuh Masa',
    'Operations': 'Operasi',
    'Livestock Care Specialist': 'Pakar Penjagaan Ternakan',
    'Livestock': 'Ternakan',
    'Farm Equipment Operator': 'Pengendali Peralatan Ladang',
    'Machinery': 'Jentera',
    'Seasonal Harvester': 'Penuai Bermusim',
    'Contract': 'Kontrak',
    'Apply Now': 'Mohon Sekarang',
    // FAQ
    'Frequently Asked Questions': 'Soalan Lazim',
    'Find answers to common questions about our farm and practices.': 'Cari jawapan kepada soalan lazim mengenai ladang dan amalan kami.',
    'Are your products 100% organic?': 'Adakah produk anda 100% organik?',
    'Yes, we adhere strictly to organic farming principles. We do not use any synthetic pesticides, herbicides, or artificial fertilizers.': 'Ya, kami mematuhi prinsip pertanian organik dengan ketat. Kami tidak menggunakan sebarang racun perosak sintetik, racun rumpai, atau baja buatan.',
    'Do you offer farm tours?': 'Adakah anda menawarkan lawatan ladang?',
    'We offer guided farm tours during the spring and summer months. Please check our Services page or contact us to book a slot.': 'Kami menawarkan lawatan ladang berpandu sepanjang tahun. Sila semak halaman Perkhidmatan kami atau hubungi kami untuk menempah slot.',
    'Where can I buy your produce?': 'Di manakah saya boleh membeli hasil tanaman anda?',
    'Our produce is available for wholesale delivery, and can also be purchased at local farmers\' markets and selected organic grocery stores in the region.': 'Hasil kami tersedia untuk penghantaran borong, dan juga boleh dibeli terus dari ladang atau kedai-kedai terpilih di rantau ini.',
    'How do you handle pest control organically?': 'Bagaimanakah anda mengendalikan kawalan perosak secara organik?',
    'We use integrated pest management (IPM) techniques, including introducing beneficial insects, crop rotation, and natural botanical repellents.': 'Kami menggunakan teknik pengurusan perosak bersepadu (IPM), termasuk memperkenalkan serangga bermanfaat, penggiliran tanaman dan penghalau botani semula jadi.',
    'Do you deliver to residential addresses?': 'Adakah anda menghantar ke alamat kediaman?',
    'Currently, we only provide wholesale delivery to businesses. However, individuals can purchase our products via our retail partners.': 'Pada masa ini, kami hanya menyediakan penghantaran borong kepada perniagaan. Walau bagaimanapun, individu boleh membeli produk kami melalui rakan kongsi runcit kami.',
    // Contact
    'Have a question about our products, services, or want to schedule a visit? We\'d love to hear from you.': 'Mempunyai soalan mengenai produk, perkhidmatan kami, atau ingin menjadualkan lawatan? Kami ingin mendengar daripada anda.',
    'Send Us a Message': 'Hantar Mesej Kepada Kami',
    'First Name': 'Nama Pertama',
    'Last Name': 'Nama Akhir',
    'Email Address': 'Alamat Emel',
    'Message': 'Mesej',
    'Send Message': 'Hantar Mesej',
    'Get In Touch': 'Hubungi Kami',
    'Our Location': 'Lokasi Kami',
    'Agricultural District': 'Daerah Pertanian',
    'Operating Hours': 'Waktu Operasi',
    'Mon - Fri: 8:00 AM - 5:00 PM': 'Isn - Jum: 8:00 PG - 5:00 PTG',
    'Sat: 9:00 AM - 1:00 PM': 'Sabtu: 9:00 PG - 1:00 PTG',
    'Sun: Closed': 'Ahad: Tutup',
    'Phone': 'Telefon',
    'Email': 'Emel',
  },
  en: {
    'Home': 'Home',
    'About Us': 'About Us',
    'Products': 'Products',
    'Services': 'Services',
    'Gallery': 'Gallery',
    'Sustainability': 'Sustainability',
    'News': 'News',
    'Careers': 'Careers',
    'FAQ': 'FAQ',
    'Contact': 'Contact',
    // Layout
    'Follow us:': 'Follow us:',
    'Quick Links': 'Quick Links',
    'Contact Info': 'Contact Info',
    'Newsletter': 'Newsletter',
    'Subscribe for seasonal updates and farm news.': 'Subscribe for seasonal updates and farm news.',
    'Your email address': 'Your email address',
    'Subscribe': 'Subscribe',
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    // Home
    'Cultivating Excellence,<br />Nurturing Nature.': 'Cultivating Excellence,<br />Nurturing Nature.',
    'Welcome to Usin Farm Enterprise. Premium agriculture, sustainable practices, and fresh produce straight from our fields to your table.': 'Welcome to Usin Farm Enterprise. Premium agriculture, sustainable practices, and fresh produce straight from our fields to your table.',
    'Explore Our Produce': 'Explore Our Produce',
    'Discover Our Story': 'Discover Our Story',
    'Why Choose Usin Farm?': 'Why Choose Usin Farm?',
    '100% Organic': '100% Organic',
    'Our crops are grown without synthetic pesticides or fertilizers, ensuring pure, natural goodness.': 'Our crops are grown without synthetic pesticides or fertilizers, ensuring pure, natural goodness.',
    'Sustainable Methods': 'Sustainable Methods',
    'We employ eco-friendly farming techniques that enrich the soil and protect local biodiversity.': 'We employ eco-friendly farming techniques that enrich the soil and protect local biodiversity.',
    'Fresh Daily': 'Fresh Daily',
    'Harvested at the peak of ripeness and delivered fresh, guaranteeing maximum nutrition and flavor.': 'Harvested at the peak of ripeness and delivered fresh, guaranteeing maximum nutrition and flavor.',
    'A Legacy of Quality Farming': 'A Legacy of Quality Farming',
    'At Usin Farm Enterprise, agriculture isn\'t just an industry—it\'s our heritage. Spanning acres of fertile land, our farm combines traditional wisdom with modern innovation to cultivate crops and raise livestock of unparalleled quality.': 'At Usin Farm Enterprise, agriculture isn\'t just an industry—it\'s our heritage. Spanning acres of fertile land, our farm combines traditional wisdom with modern innovation to cultivate crops and raise livestock of unparalleled quality.',
    'Premium Livestock Breeding': 'Premium Livestock Breeding',
    'Seasonal Organic Vegetables': 'Seasonal Organic Vegetables',
    'Advanced Irrigation Systems': 'Advanced Irrigation Systems',
    'Community-Supported Agriculture': 'Community-Supported Agriculture',
    'Learn More About Us': 'Learn More About Us',
    'Years of<br/>Excellence': 'Years of<br/>Excellence',
    // About
    'About Usin Farm': 'About Usin Farm',
    'Rooted in tradition, growing towards the future.': 'Rooted in tradition, growing towards the future.',
    'Our History': 'Our History',
    'Founded on a deep respect for the land, Usin Farm Enterprise began as a humble family endeavor. Over the years, we have expanded our acreage and our expertise, transforming into a premier agricultural supplier.': 'Founded on a deep respect for the land, Usin Farm Enterprise began as a humble family endeavor. Over the years, we have expanded our acreage and our expertise, transforming into a premier agricultural supplier.',
    'Despite our growth, our core philosophy remains unchanged: to work in harmony with nature to produce food that is healthy for both our community and our planet.': 'Despite our growth, our core philosophy remains unchanged: to work in harmony with nature to produce food that is healthy for both our community and our planet.',
    'Acres of Land': 'Acres of Land',
    'Happy Customers': 'Happy Customers',
    'Our Mission': 'Our Mission',
    'To cultivate premium quality agricultural products through sustainable and innovative farming practices, ensuring food security and nutrition for our community.': 'To cultivate premium quality agricultural products through sustainable and innovative farming practices, ensuring food security and nutrition for our community.',
    'Our Vision': 'Our Vision',
    'To be the leading recognized model of sustainable and regenerative agriculture in the region, inspiring a greener, healthier world.': 'To be the leading recognized model of sustainable and regenerative agriculture in the region, inspiring a greener, healthier world.',
    'Core Values': 'Core Values',
    'Integrity in our methods, transparency with our consumers, and an unwavering commitment to environmental stewardship.': 'Integrity in our methods, transparency with our consumers, and an unwavering commitment to environmental stewardship.',
    'Community First': 'Community First',
    'We believe a farm is the heart of a community. We actively support local initiatives and prioritize fair labor practices.': 'We believe a farm is the heart of a community. We actively support local initiatives and prioritize fair labor practices.',
    // Products
    'Our Products & Livestock': 'Our Products & Livestock',
    'From our farm straight to you. Explore the range of fresh, healthy, and high-quality livestock produce from Usin Farm Enterprise.': 'From our farm straight to you. Explore the range of fresh, healthy, and high-quality livestock produce from Usin Farm Enterprise.',
    'Cattle Farming': 'Cattle Farming',
    'Quality Beef Cattle': 'Quality Beef Cattle',
    'Local & Crossbreed Cattle': 'Local & Crossbreed Cattle',
    'Healthy & Well-cared': 'Healthy & Well-cared',
    'Broiler Chicken': 'Broiler Chicken',
    'Fresh Broiler Meat': 'Fresh Broiler Meat',
    'High Quality Diet': 'High Quality Diet',
    'Optimum Growth': 'Optimum Growth',
    'Free-range Chicken': 'Free-range Chicken',
    'Authentic Free-range Chicken': 'Authentic Free-range Chicken',
    'Free-roaming Farm': 'Free-roaming Farm',
    'Firm & Tasty Meat': 'Firm & Tasty Meat',
    'Duck Farming': 'Duck Farming',
    'Meat Ducks': 'Meat Ducks',
    'Laying Ducks': 'Laying Ducks',
    'Clean Farming Environment': 'Clean Farming Environment',
    'Fresh Duck Eggs': 'Fresh Duck Eggs',
    'Grade A Fresh Duck Eggs': 'Grade A Fresh Duck Eggs',
    'Beautiful & Quality Yolks': 'Beautiful & Quality Yolks',
    'Rich in Nutrients': 'Rich in Nutrients',
    'Salted Eggs': 'Salted Eggs',
    'Authentic Salted Eggs': 'Authentic Salted Eggs',
    'Traditional Processing': 'Traditional Processing',
    'Suitable for Various Dishes': 'Suitable for Various Dishes',
    'Contact Us': 'Contact Us',
    // Services
    'Farm Services': 'Farm Services',
    'Beyond growing premium crops, Usin Farm Enterprise provides essential services to support the broader agricultural ecosystem and community.': 'Beyond growing premium crops, Usin Farm Enterprise provides essential services to support the broader agricultural ecosystem and community.',
    'Wholesale Delivery': 'Wholesale Delivery',
    'Reliable, temperature-controlled delivery of fresh produce and meats directly to restaurants, supermarkets, and local businesses.': 'Reliable, temperature-controlled delivery of fresh produce and meats directly to restaurants, supermarkets, and local businesses.',
    'Agricultural Consultation': 'Agricultural Consultation',
    'Expert advice on crop rotation, soil health, and sustainable farming methods for new and transitioning farmers.': 'Expert advice on crop rotation, soil health, and sustainable farming methods for new and transitioning farmers.',
    'Storage Solutions': 'Storage Solutions',
    'State-of-the-art cold storage and grain silos available for seasonal rent to help manage harvest overflow.': 'State-of-the-art cold storage and grain silos available for seasonal rent to help manage harvest overflow.',
    'Farm Tours & Education': 'Farm Tours & Education',
    'Immersive guided tours for schools and families to learn about where their food comes from and how it\'s grown.': 'Immersive guided tours for schools and families to learn about where their food comes from and how it\'s grown.',
    'Inquire Now &rarr;': 'Inquire Now &rarr;',
    // Gallery
    'Farm Gallery': 'Farm Gallery',
    'Take a visual tour through Usin Farm Enterprise. From our golden harvests to our healthy livestock.': 'Take a visual tour through Usin Farm Enterprise. From our golden harvests to our healthy livestock.',
    'Play Video': 'Play Video',
    'View Image': 'View Image',
    // Sustainability
    'Our Commitment to the Earth': 'Our Commitment to the Earth',
    'At Usin Farm, we believe that true agricultural success is measured by the health of the ecosystem. We have implemented comprehensive sustainable practices to ensure our land remains fertile for generations.': 'At Usin Farm, we believe that true agricultural success is measured by the health of the ecosystem. We have implemented comprehensive sustainable practices to ensure our land remains fertile for generations.',
    'Read Our Impact Report': 'Read Our Impact Report',
    'Key Initiatives': 'Key Initiatives',
    'Zero Waste': 'Zero Waste',
    'Composting all organic waste to create natural fertilizers.': 'Composting all organic waste to create natural fertilizers.',
    'Water Conservation': 'Water Conservation',
    'Advanced drip irrigation reducing water usage by 40%.': 'Advanced drip irrigation reducing water usage by 40%.',
    'Solar Powered': 'Solar Powered',
    'Our facilities operate on 100% renewable solar energy.': 'Our facilities operate on 100% renewable solar energy.',
    'Soil Health': 'Soil Health',
    'Practicing crop rotation to maintain rich, nutrient-dense soil.': 'Practicing crop rotation to maintain rich, nutrient-dense soil.',
    // News
    'Farm News': 'Farm News',
    'Stay updated with the latest happenings, seasonal harvests, and agricultural innovations at Usin Farm.': 'Stay updated with the latest happenings, seasonal harvests, and agricultural innovations at Usin Farm.',
    'Spring Harvest Festival Announced': 'Spring Harvest Festival Announced',
    'May 15, 2025': 'May 15, 2025',
    'Join us for our annual harvest festival featuring farm tours, local artisan markets, and live music.': 'Join us for our annual harvest festival featuring farm tours, local artisan markets, and live music.',
    'New Sustainable Irrigation System Installed': 'New Sustainable Irrigation System Installed',
    'April 22, 2025': 'April 22, 2025',
    'We\'re excited to announce the completion of our new smart irrigation project, reducing water waste by 40%.': 'We\'re excited to announce the completion of our new smart irrigation project, reducing water waste by 40%.',
    'Usin Farm Awarded Organic Certification': 'Usin Farm Awarded Organic Certification',
    'March 10, 2025': 'March 10, 2025',
    'After years of dedication, we have officially received our regional Organic Farm certification.': 'After years of dedication, we have officially received our regional Organic Farm certification.',
    'Read More &rarr;': 'Read More &rarr;',
    // Careers
    'Join Our Team': 'Join Our Team',
    'Grow your career with us. We\'re always looking for passionate individuals who care about sustainable agriculture.': 'Grow your career with us. We\'re always looking for passionate individuals who care about sustainable agriculture.',
    'Open Positions': 'Open Positions',
    'Senior Agronomist': 'Senior Agronomist',
    'Full-Time': 'Full-Time',
    'Operations': 'Operations',
    'Livestock Care Specialist': 'Livestock Care Specialist',
    'Livestock': 'Livestock',
    'Farm Equipment Operator': 'Farm Equipment Operator',
    'Machinery': 'Machinery',
    'Seasonal Harvester': 'Seasonal Harvester',
    'Contract': 'Contract',
    'Apply Now': 'Apply Now',
    // FAQ
    'Frequently Asked Questions': 'Frequently Asked Questions',
    'Find answers to common questions about our farm and practices.': 'Find answers to common questions about our farm and practices.',
    'Are your products 100% organic?': 'Are your products 100% organic?',
    'Yes, we adhere strictly to organic farming principles. We do not use any synthetic pesticides, herbicides, or artificial fertilizers.': 'Yes, we adhere strictly to organic farming principles. We do not use any synthetic pesticides, herbicides, or artificial fertilizers.',
    'Do you offer farm tours?': 'Do you offer farm tours?',
    'We offer guided farm tours during the spring and summer months. Please check our Services page or contact us to book a slot.': 'We offer guided farm tours during the spring and summer months. Please check our Services page or contact us to book a slot.',
    'Where can I buy your produce?': 'Where can I buy your produce?',
    'Our produce is available for wholesale delivery, and can also be purchased at local farmers\' markets and selected organic grocery stores in the region.': 'Our produce is available for wholesale delivery, and can also be purchased at local farmers\' markets and selected organic grocery stores in the region.',
    'How do you handle pest control organically?': 'How do you handle pest control organically?',
    'We use integrated pest management (IPM) techniques, including introducing beneficial insects, crop rotation, and natural botanical repellents.': 'We use integrated pest management (IPM) techniques, including introducing beneficial insects, crop rotation, and natural botanical repellents.',
    'Do you deliver to residential addresses?': 'Do you deliver to residential addresses?',
    'Currently, we only provide wholesale delivery to businesses. However, individuals can purchase our products via our retail partners.': 'Currently, we only provide wholesale delivery to businesses. However, individuals can purchase our products via our retail partners.',
    // Contact
    'Have a question about our products, services, or want to schedule a visit? We\'d love to hear from you.': 'Have a question about our products, services, or want to schedule a visit? We\'d love to hear from you.',
    'Send Us a Message': 'Send Us a Message',
    'First Name': 'First Name',
    'Last Name': 'Last Name',
    'Email Address': 'Email Address',
    'Message': 'Message',
    'Send Message': 'Send Message',
    'Get In Touch': 'Get In Touch',
    'Our Location': 'Our Location',
    'Agricultural District': 'Agricultural District',
    'Operating Hours': 'Operating Hours',
    'Mon - Fri: 8:00 AM - 5:00 PM': 'Mon - Fri: 8:00 AM - 5:00 PM',
    'Sat: 9:00 AM - 1:00 PM': 'Sat: 9:00 AM - 1:00 PM',
    'Sun: Closed': 'Sun: Closed',
    'Phone': 'Phone',
    'Email': 'Email',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ms');

  const t = (key: string, defaultValue?: string) => {
    return translations[language][key] || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
